name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests-with-coverage:
    name: Tests and Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install poetry
        run: pip install poetry
      - name: Run poetry install
        run: poetry install
      - name: Run tests and collect coverage
        run: poetry run pytest tests/ -v -s --cov=sampy --cov-report=xml --cov-config=.coveragerc
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
